<template>
  <div
    id="visionSection"
    class="Section"
  >
    <h1
      id="hrcontact"
    >
      Vision
    </h1>
    <div class="Explain">
      今後のビジョンを記載します。今後はバック・フロント関係なく幅広く知識を身につけた後に、
      フロントエンドに関してより専門的に学んでいこうと考えています。
      その後、デザインや分析などの知識も身につけたいです。
      自分に厳しく、日々精進の心を忘れずに頑張ろうと思います。
      周りの人への感謝を忘れずに頑張ります。
    </div>
  </div>
</template>
